[package]
name = "transit_model_procmacro"
version = "0.1.0"
authors = ["Guillaume Pinot <texitoi@texitoi.eu>"]
license = "AGPL-3.0-only"
description = "A private procmacro crate for the transit_model crate"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
